### ISSUE TITLE
Update Inventory on profile page

### ISSUE THREAD

**Issue by Eriken79** [MohamedCheour98/BreakBread#25]
When "Add Grocery Run", reset the inventory attribute of the user to an empty list. 

When "Finish Run" is clicked, add the items that belong to the user to its inventory list on the profile page. 

Time Estimate: 5 Hrs
Erik: 5 Hrs
Joseph: 1hr

**Comment by josephos416** [comment]
now added indexes to the items. Moved around the buttons and and added add and delete buttons.

**Comment by josephos416** [comment]
updated the profile page to be updated when return from grocery page
